name: Append Link

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Link to add'
        required: true
        type: string

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Show current data.json
        run: cat data/data.json

      - name: Add URL to data.json
        run: |
          echo "Adding: ${{ github.event.inputs.url }}"
          jq --arg url "${{ github.event.inputs.url }}" '. |= [$url] + .' data/data.json > tmp.json
          cat tmp.json
          mv tmp.json data/data.json

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/data.json
          git diff --staged
          git commit -m "Add link: ${{ github.event.inputs.url }}" || echo "No changes to commit"
          git push
